version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 250M
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - .volume/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 2s
      timeout: 20s
      retries: 30

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2182:2181
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    labels:
      NAME: zookeeper
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 2s
      timeout: 3s
      retries: 30

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    container_name: kafka
    ports:
      - 9093:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: products-event:1:1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    labels:
      NAME: kafka
    volumes:
      - kafka:/data
    healthcheck:
      test: ["CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list"]
      interval: 2s
      timeout: 3s
      retries: 30
    depends_on:
      - zookeeper

volumes:
  kafka:
    driver: local


      ## Lembrar de setar para app:
      #
      # depends_on:
      #     condition: service_healthy 



