all:
  children:
    aws:
      hosts:
        vm_aws_01:
          ansible_host: "{{ lookup('env', 'AWS_VM_01_PUBLIC_IP') }}"
          ansible_port: 22
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env', 'AWS_PRIVATE_KEY_FILE') }}"
    lab:
      hosts:
        vm_lab_01:
          ansible_host: andromeda.lasdpc.icmc.usp.br
          ansible_port: 21111
          ansible_user: gcloud13
          ansible_password: "{{ lookup('env', 'LAB_SSH_PASS') }}"

