all:
  hosts:
    vm_aws_01:
      ansible_host: "{{ lookup('env', 'AWS_VM_01_PUBLIC_IP') }}"
      ansible_port: 22
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ lookup('env', 'AWS_PRIVATE_KEY_FILE') }}"
