- hosts: all
  become: true
  vars:
    app_dir: /home/gcloud13
  tasks:
    - name: Copiando 'docker-compose.yaml'
      copy:
        src: ../docker-compose.yaml
        dest: "{{ app_dir }}"
    
    - name: Copiando configurações do worker
      copy:
        src: ../../app/worker-extractor/config
        dest: "{{ app_dir }}"

    - name: Copiando credenciais do worker
      copy:
        src: ../../app/worker-extractor/secret
        dest: "{{ app_dir }}"
    
    - name: Copiando schemas
      copy:
        src: ../../app/schemas
        dest: "{{ app_dir }}"

    - name: Docker compose up
      command: docker-compose --compatibility up -d
      args:
        chdir: "{{ app_dir }}"
