- hosts: all
  become: true
  vars:
    app_dir: /home/gcloud13
  tasks:    
    - name: Copiando configurações do worker
      copy:
        src: ../../app/worker-extractor/config
        dest: "{{ app_dir }}"

    - name: Copiando credenciais do worker
      copy:
        src: ../../app/worker-extractor/secret
        dest: "{{ app_dir }}"

    - name: Copiando schemas
      copy:
        src: ../../app/schemas
        dest: "{{ app_dir }}"

    - name: Docker compose restart
      docker_compose:
        project_src: "{{ app_dir }}"
        state: present
        restarted: yes
        services: 
          - worker-extractor