- hosts: all
  become: true
  vars:
    app_dir: /home/gcloud13
    host_env:
      MYSQL_PASSWORD: "{{ lookup('env', 'DB_PASSWORD') }}"
      MYSQL_ROOT_PASSWORD: "{{ lookup('env', 'DB_PASSWORD') }}"
      CONTAINER_REGISTRY_URL: registry.gitlab.com
    container_registry_user:  gcloud13-deploy-token
    container_registry_password: "{{ lookup('env', 'GITLAB_DEPLOY_TOKEN') }}"
  tasks:
    - name: Setando variaveis de ambiente
      lineinfile:
        dest: /etc/environment
        line: "{{ item.key }}={{ item.value }}"
      loop: "{{ host_env | dict2items }}"
      
    - name: Apt update e instalando dependencias
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
    
    - name: Buscando chave do repositorio apt do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionando repositorio apt do Docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Apt update e instalando pacotes do Docker
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose

    - name: Instalando SDK do Docker via pip
      pip:
        name: docker

    - name: Criando diretorio do projeto
      file:
        path: "{{ app_dir }}"
        state: directory
      
    - name: Docker login no registry
      docker_login:
        registry: registry.gitlab.com
        username: "{{ container_registry_user }}"
        password: "{{ container_registry_password }}"
